#ifndef SMART_INVENTORY_SCALE_DEVICE_H
#define SMART_INVENTORY_SCALE_DEVICE_H

/**
 * @file SmartInventoryScaleDevice.h
 * @brief Declares the SmartInventoryScaleDevice class for the Restock embedded application.
 *
 * SmartInventoryScaleDevice represents the physical smart inventory device used by Restock.
 * It will coordinate environmental sensing, weight monitoring, local display
 * updates and telemetry delivery to the Edge Service.
 *
 * For the initial setup, this class only validates the application lifecycle.
 * Sensor readings and telemetry behavior will be added incrementally.
 *
 * @author UI-Topic Team
 * @date May 2026
 * @version 0.1
 */

#include "Device.h"

class SmartInventoryScaleDevice : public Device {
private:
    unsigned long lastUpdateTime;
    static const unsigned long UPDATE_INTERVAL_MS = 2000;

public:
    /**
     * @brief Constructs a SmartInventoryScaleDevice device.
     */
    SmartInventoryScaleDevice();

    /**
     * @brief Initializes the smart inventory scale device.
     */
    void begin();

    /**
     * @brief Executes recurrent device behavior.
     */
    void update();

    /**
     * @brief Handles events generated by sensors.
     *
     * @param event Event received by the device.
     */
    void on(Event event) override;

    /**
     * @brief Handles commands sent to the device.
     *
     * @param command Command received by the device.
     */
    void handle(Command command) override;
};

#endif